version: '2'

services:
  template:
    build:
      context: .
      dockerfile: toasts/template/Dockerfile
    volumes:
      - ./basement/docker-entrypoint.sh:/docker-entrypoint.sh
      - ./basement/scripts:/scripts
      - ./toasts/template/:/var/www/repo
    env_file:
      - ./toasts/template/.env
    ports:
      - 4000:3000
    restart: always
